assert(SMODS.load_file('globals.lua'))()
assert(SMODS.load_file('jokers.lua'))()
assert(SMODS.load_file('boosters.lua'))()
assert(SMODS.load_file('tags.lua'))()
assert(SMODS.load_file('challenges.lua'))()