# removes base game lucky card functionality, which is then re-implemented by the mod, making sure it's compatible with the Cat joker

[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_p_dollars()
    if self.debuff then return 0 end
    local ret = 0
    if self.seal == 'Gold' then
        ret = ret +  3
    end
    if self.ability.p_dollars > 0 then
        if self.ability.effect == "Lucky Card" then 
            if pseudorandom('lucky_money') < G.GAME.probabilities.normal/15 then
                self.lucky_trigger = true
                ret = ret +  self.ability.p_dollars
            end
        else 
            ret = ret + self.ability.p_dollars
        end
    end
    if ret > 0 then 
        G.GAME.dollar_buffer = (G.GAME.dollar_buffer or 0) + ret
        G.E_MANAGER:add_event(Event({func = (function() G.GAME.dollar_buffer = 0; return true end)}))
    end
    return ret
end'''
position = "at"
payload = '''function Card:get_p_dollars()
    if self.debuff then return 0 end
    local ret = 0
    if self.seal == 'Gold' then
        ret = ret +  3
    end
    if self.ability.p_dollars > 0 and self.ability.effect ~= "Lucky Card" then
        ret = ret + self.ability.p_dollars
    end
    if ret > 0 then 
        G.GAME.dollar_buffer = (G.GAME.dollar_buffer or 0) + ret
        G.E_MANAGER:add_event(Event({func = (function() G.GAME.dollar_buffer = 0; return true end)}))
    end
    return ret
end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_chip_mult()
    if self.debuff then return 0 end
    if self.ability.set == 'Joker' then return 0 end
    if self.ability.effect == "Lucky Card" then 
        if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then
            self.lucky_trigger = true
            return self.ability.mult
        else
            return 0
        end
    else  
        return self.ability.mult
    end
end'''
position = "at"
payload = '''function Card:get_chip_mult()
    if self.debuff then return 0 end
    if self.ability.set == 'Joker' then return 0 end
    if self.ability.effect ~= "Lucky Card" then return self.ability.mult end
end'''
match_indent = true
times = 1