[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if pseudorandom('lucky_money') < G.GAME.probabilities.normal/15 then'''
position = "at"
payload = '''if next(SMODS.find_card('j_l6_luckylegends_cat')) or pseudorandom('lucky_money') < G.GAME.probabilities.normal/15 then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then'''
position = "at"
payload = '''if next(SMODS.find_card('j_l6_luckylegends_cat')) or pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then'''
match_indent = true
times = 1